#!/usr/bin/env sh

# https://docs.cachix.org/pushing#flakes

cache=ruby0b-shinobu-bot-hs

echo ">>> Pushing flake inputs..."
nix flake archive --json \
  | jq -r '.path,(.inputs|to_entries[].value.path)' \
  | cachix push "$cache"

echo ">>> Pushing runtime closure..."
nix build --json \
  | jq -r '.[].outputs | to_entries[].value' \
  | cachix push "$cache"
